# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            AbRegen Pty Ltd
tagline:          Sample
url:              
paginate:         1
baseurl:          /
author:
  name:           Nitin Malpe
  url:            malpenitin@gmail.com
  email:          malpenitin@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/malpenitin/abregen


# Menu Structure
menu:
- group:        1
  title:        Home
  url:          ""
  hassubmenu:   false
- group:        2
  title:        Board and Management
  url:          board_and_management
  hassubmenu:   false
- group:        3
  title:        Technology
  url:          ""
  hassubmenu:   true
  submenu:
  - subitem:    1
    title:      Flightless I
    url:        flightless_I
  - subitem:    2
    title:      Publications
    url:        publications
- group:        4
  title:        Therapeutic Focus
  url:          therapeutic_focus
  hassubmenu:   false
- group:        6
  title:        News
  url:          news
  hassubmenu:   false
- group:        5
  title:        Contact
  url:          contact
  hassubmenu:   false



